services:
  - type: web
    name: simulador-back
    plan: free
    region: oregon
    buildCommand: docker build -t simulador-back .
    startCommand: docker run -p 8080:8080 simulador-back
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-damp-flower-acipxo0w-pooler.sa-east-1.aws.neon.tech:5432/simulador?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_Qvd9BnO6eXcE
